### ISSUE TITLE
一些架构上的建议

### ISSUE THREAD

**Issue by iceBear67** [CatkatPowered/kat-server#1]
~~纯路人,看到hanbings开坑来看看~~  

声明：本人不是什么专业架构师，只是发表一下自己的看法  

1. KatMessageType 应该使用 enum  

为什么要使用 constant 的做法呢？这样没法享受到 enum 的序列化以及他自带的一系列方法，还有编译期检查。  
另外我注意到 KMT 本身的注释是`消息类型管理器`，我认为至少语义上应该把 Manager 和 MessageType 分离开来，一个类不应该有太多职责。（单一职责原则）

2. 尽量减少没有必要的静态代码  

kat-server 内部大量使用了静态，甚至 `KatExtensionManager` 这样的封装几乎都是由静态方法构成的外观，并且有尝试用静态来模拟单例模式的倾向。但实际上我们应该尽量使用`依赖注入`的做法而不是`tons of static and singletons`，因为那样的耦合度*更高*，更不利于单元测试，而且想引入新的实现，或者进行更多封装也较为困难。  

> 此外,使用静态来模拟单例会导致类字段中初始化顺序的微妙差异产生的 bug。

针对「过多的使用静态」这一点，我认为应该对所有完全用静态实现的功能重新考虑，因为这很不面向对象编程  

3. 请抽象

上文提到了将 Manager 抽象，但不只是 Manager 需要抽象。KatServer 中存在很多有共性的地方，他们都可以抽象来享受多态带来的好处，比如 Storage，DatabaseConnector。    

4. 非必要请不要使用包装类型

非必要的装箱拆箱会大幅度影响效率。

https://github.com/CatkatPowered/kat-server/blob/9f0e35dd47c80b6d14b510352ccc7df8c6f63a68/src/main/java/com/catkatpowered/katserver/storage/KatMediaStorage.java#L10

5.  Manager 的职责太多了

初始化工作就不应该 manager 做，至少不应该是个 static void Main     
完全可以在主类里完成所有组件的装配再统一暴露一个封装啊  

6. 有时候暴露的事情太多了

举个例子,`KatServer`
虽然说很多都是 Repeat-Your-Self，但是其中也不缺乏一些像是 `loadExtensions` 这种只应该在初始化的时候调用一次的东西...... 甚至还有意义不明的 https://github.com/CatkatPowered/kat-server/blob/9f0e35dd47c80b6d14b510352ccc7df8c6f63a68/src/main/java/com/catkatpowered/katserver/KatServer.java#L70-72

---

就先写这些吧...

**Comment by Krysztal112233** [comment]
感谢你对架构上的建议。

我是目前重构架构的工作者之一，我回复一些内容。

- KatMessageType设计之初是面向可拓展的聚合消息类型，实际上KatServer本体是对消息不敏感的。但是对于聊天平台来说是敏感的，也就是说我们只能假定通用情况下存在这些组合，但是我们不能保证平台的特殊性，诸如Discord的`RichMsg`，这是不存在于QQ上的。考虑到这一点，相比之下`enum`的序列化特性并不能有足够的吸引力，他并没有足够强大的拓展能力。关于分离`KatUniMessageType`和`KatUniMessageTypeManager`是我重构目标内的内容。
- 静态初始化顺序是我在考虑的事情，但是这部分代码实际上不是我写的。
- 关于抽象数据库，这部分代码完成度实在是太低了，实在是没办法处理。
- 关于抽象出业务逻辑，这是这段时间的重构内容之一
- `Kat**Manager`的职责也是我重构任务，毕竟实际上他没能阻止重复初始化，大概也算是设计上的失误。
- 关于装箱的问题，如果假设这个项目目标就是高并发的话确实会影响效率，但是说实话就算不高并发，也不该用`Bool`装箱类型，这算是设计上的失误。
- 关于暴露的多少，我认为需要商讨。因为这个项目原始设计是面向插件， @Hanbings 对于暴露API设计之初参照的是`Spigot`，`CraftBukkit`等成熟的插件项目。
- 最后一点，这个是带名字的`logger`。可以不用，但是用了效果更好。

以及大量的`static`是最初设计上没有采用`MVC`导致的。

关于近期重构的内容，几乎和你所说的一致。大概我们确实有相同的想法（

**Comment by iceBear67** [comment]
katMessageType那里可以考虑用接口来做。这样内置的支持可以enum Xx implements KatMessageType，毫无违和感。

**Comment by iceBear67** [comment]
面向插件的话，其实我不太建议把整个程序就当作是api来处理。可以引入依赖注入框架和api-实现分离，以此达到「隐藏不必要的东西」

- 在重构的时候可以考虑这一点。设计出大量抽象类来构造出这一层，像是 Bukkit 与 CraftBukkit

**Comment by iceBear67** [comment]
Logger 我也比较建议类自行保管（Lombok的@Slf4j @Log4j)，如果有处于效率考虑那就无可厚非，因为要多分配几个logger

**Comment by iceBear67** [comment]
感谢您的回复 :heart:

**Comment by SUIBING112233** [comment]
> 

这一点也在本次重构当中

**Comment by Krysztal112233** [comment]
> 面向插件的话，其实我不太建议把整个程序就当作是api来处理。可以引入依赖注入框架和api-实现分离，以此达到「隐藏不必要的东西」
> 
>     * 在重构的时候可以考虑这一点。设计出大量抽象类来构造出这一层，像是 Bukkit 与 CraftBukkit

这一点也在重构内容之中

**Comment by Krysztal112233** [comment]
> katMessageType那里可以考虑用接口来做。这样内置的支持可以enum Xx implements KatMessageType，毫无违和感。

是个不错的想法 但是依然需要考虑。因为其实MsgType是核心无关，他到底是什么其实并不影响

**Comment by iceBear67** [comment]
> > katMessageType那里可以考虑用接口来做。这样内置的支持可以enum Xx implements KatMessageType，毫无违和感。
> 
> 是个不错的想法 但是依然需要考虑。因为其实MsgType是核心无关，他到底是什么其实并不影响

可以直接丢掉 message type。做一套 message event 体系就好了，剩下的不如让类型系统来解决

**Comment by Krysztal112233** [comment]
基本上提到的问题已经修改完毕，感谢反馈
