### ISSUE TITLE
🤔 Feat: Is it necessary to write our own download utility？

### ISSUE THREAD

**Issue by Krysztal112233** [CatkatPowered/kat-server#14]
如题所示，当前面临着一个问题：是否需要编写我们自己的下载工具类像是 `DownloadUtils.java` ?

[`LocalProvider.java`](https://github.com/CatkatPowered/kat-server/blob/main/src/main/java/com/catkatpowered/katserver/storage/providers/local/LocalProvider.java) 作为内置的资源文件储存提供者，需要用到一些下载功能，因此当前面临以下问题

若是使用外部依赖：

- 额外庞大的依赖
- 对于文档不熟悉导致整体功能错误
- 可能和此项目集成较差，难以管理

若是此项目自己编写诸如 `DownloadUtils.java` 的下载工具类

- 可能会增加维护负担。
- 部分下载功能实现困难

从总体上看当前只有 [`LocalProvider.java`](https://github.com/CatkatPowered/kat-server/blob/main/src/main/java/com/catkatpowered/katserver/storage/providers/local/LocalProvider.java) 需要使用下载功能，是否有必要因为小部分需求引入额外的依赖，亦或者编写实用工具类？

**Comment by hanbings** [comment]
涉及到关于性能和安全问题，持保留意见，偏向于用第三方库
1. 性能保证
2. 由社区维护
3. 封装第三方库并提供合理向外的 API
4. 从一定性能角度来说，无论是单线程还是多线程下载技术都会比自己编写的工具类更为成熟

**Comment by 4o3F** [comment]
赞成使用第三方库

1. 减轻我们的维护成本
2. 同寒冰，第三方库更为成熟，且相比之下性能更好

`KatNetworkTest`里面用了OkHttp，直接把那个换成全局依赖就可

**Comment by Krysztal112233** [comment]
那么以后 `KatServer` 内置的下载工具将会使用 `OkHttp` 作为依赖编写。
