### ISSUE TITLE
🤔 Question: Should `KatResource` and `KatUniMessage` be combined?

### ISSUE THREAD

**Issue by 4o3F** [CatkatPowered/kat-server#17]
`KatUniMessage`与`KatResource`中的`hash`,`uri`等部分有功能重叠, 目前进行一部分网络模块更改后已不再需要`KatResource`等对文件的针对性设计。
我初步设计的文件传输流程详见[网络部分](https://protocol.catkatpowered.com/#/http)
现询问其他模块是否会因此次重构受到影响，同时征集更好的方案

**Comment by Krysztal112233** [comment]
我注意到文档中存在这样一句话：

> mosseger => kat-server 发送 WebsocketMessagePacket, 其中包含的 KatUniMessage 包含文件的 hash 以及一次性鉴权 token, 此时的 KatUniMessage 的 isDownloadable 应为 false

请问这是什么意思？

以及当前的设计上，文件上传的流程如何？是否是由 `StorageProviders` 进行下载？

**Comment by 4o3F** [comment]
文件上传时，客户端先通过HTTP POST把文件上传并拿到一个token(此时HTTP Handler会把文件传送给StorageProvider)
再通过websocket发送消息，然后再正常处理消息

**Comment by Krysztal112233** [comment]
所以最终由 `StorageProviders` 管理文件的下载是吗？

**Comment by 4o3F** [comment]
> 所以最终由 `StorageProviders` 管理文件的下载是吗？

不，文件下载由network模块里的HTTPHandler来完成，`StorageProviders` 只负责储存文件，也可以说成是
`StorageProviders` 从HTTPHandler中下载文件，此时下载是抽象的

**Comment by Krysztal112233** [comment]
> > 所以最终由 `StorageProviders` 管理文件的下载是吗？
> 
> 不，文件下载由network模块里的HTTPHandler来完成，`StorageProviders` 只负责储存文件，也可以说成是 `StorageProviders` 从HTTPHandler中下载文件，此时下载是抽象的

那么我们需要划定默认行为，比如由 `HTTPHandler` 下载文件到一个位置，最后调用 `StorageProviders` 的upload方法将其移动到合适的位置？

**Comment by 4o3F** [comment]
> > > 所以最终由 `StorageProviders` 管理文件的下载是吗？
> > 
> > 
> > 不，文件下载由network模块里的HTTPHandler来完成，`StorageProviders` 只负责储存文件，也可以说成是 `StorageProviders` 从HTTPHandler中下载文件，此时下载是抽象的
> 
> 那么我们需要划定默认行为，比如由 `HTTPHandler` 下载文件到一个位置，最后调用 `StorageProviders` 的upload方法将其移动到合适的位置？

直接传输数据流怎么样呢？

**Comment by Krysztal112233** [comment]
> > > > 所以最终由 `StorageProviders` 管理文件的下载是吗？
> > > 
> > > 
> > > 不，文件下载由network模块里的HTTPHandler来完成，`StorageProviders` 只负责储存文件，也可以说成是 `StorageProviders` 从HTTPHandler中下载文件，此时下载是抽象的
> > 
> > 那么我们需要划定默认行为，比如由 `HTTPHandler` 下载文件到一个位置，最后调用 `StorageProviders` 的upload方法将其移动到合适的位置？
> 
> 直接传输数据流怎么样呢？

直接传输数据流是否会造成内存占用过大？比如过大的文件等等

**Comment by 4o3F** [comment]
两个方案
1. 可以直接在上传时选择长传，然后直接实时保存
2. 上传时选择切片上传，分成若干足够小的文件传输

**Comment by Krysztal112233** [comment]
> 两个方案
> 1. 可以直接在上传时选择长传，然后直接实时保存
> 2. 上传时选择切片上传，分成若干足够小的文件传输

这两种方案是否可能受到IM资源服务器的限制？

**Comment by 4o3F** [comment]
> > 两个方案
> > 
> > 1. 可以直接在上传时选择长传，然后直接实时保存
> > 2. 上传时选择切片上传，分成若干足够小的文件传输
> 
> 这两种方案是否可能受到IM资源服务器的限制？

据我所知，没有，但可能有我没见过的，这地方的处理应该交由IM Provider进行个性化处理

**Comment by Krysztal112233** [comment]
所以这个地方将由IM Provider自行处理下载是吗？

**Comment by 4o3F** [comment]
> 所以这个地方将由IM Provider自行处理下载是吗？

不是...IM Provider下载后会传递给storage的

**Comment by Krysztal112233** [comment]
这个方面我不是很熟悉，比较顾虑内存占用问题。

@hanbings

**Comment by Krysztal112233** [comment]
当前我的想法，对于储存文件的流程如下

- IM Provider 下载文件到临时目录，下载流程交给IM Provider实现。
- IM Provider 下载文件完毕后提交包含文件信息的 `KatUniMessage` 数据到 `StorageProvider`，也就是说调用 `StorageProvider` 的`upload`方法让 `StorageProvider` 移动文件到合适的位置

**Comment by Krysztal112233** [comment]
对于 `StorageProviders` 部分已经进行了修改。

- 移除了可被替代的 `update` 函数
- 修改了 `upload` 函数的参数为 `fileHash` 和 `inputStream`

**Comment by 4o3F** [comment]
已修改完成
mark as done
