### ISSUE TITLE
🤔Question: 是否应将配置文件从YAML转变为TOML

### ISSUE THREAD

**Issue by 4o3F** [CatkatPowered/kat-server#18]
我认为从YAML转变为TOML有如下优点
+ TOML语法相较YAML更易理解
+ TOML相较于YAML更易排查错误
+ kat-boot使用C++编写，目前未能发现C++有完善安全的YAML解析器，同时为了配置文件统一，建议改为TOML

**Comment by Krysztal112233** [comment]
同意。
Link: #19
